_1sem/December_4_Task/December_4_Task/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from tasks.views import log_in

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^task/', include('tasks.urls',namespace="tasks")),
    url(r'^login',log_in, name='login'),


]

_1sem/December_4_Task/tasks/urls.py
from django.conf.urls import url
from tasks.views import *

urlpatterns = [
    url(r'^all$',show_tasks,name="all"),
    #url(r'^(?P<task_id>\d+)',show_task),
    #url(r'^add',add_task),#добавить новый task
   # url(r'^edit/(?P<task_id>\d+)',edit_task),#редактировать имеющийся task
    url(r'^(?P<task_id>\d+)$', show_task),
    url(r'^(?P<task_id>\d+)/edit', edit_task, name="edit_task"),
    url(r'^create$', create_task)
]

_1sem/December_4_Task/tasks/models.py
import datetime
from django.db import models

# Create your models here.
statuses = (
    ('T','To do'),
    ('P','in progress'),
    ('R','Review'),
    ('D','Done'),
)

class Task(models.Model):
    # text = models.TextField()
    text = models.CharField(max_length=140)
    deadline = models.DateTimeField(blank=True, null=True, default=datetime.datetime.today)
    status = models.CharField(max_length=1, choices=statuses, default="T")
    priority = models.IntegerField(default=5)

    def __str__(self):
        return "%s : %s : %s" % (self.text, self.priority, self.get_status_display())

_1sem/December_4_Task/tasks/forms.py
from django import forms

from tasks.models import Task


class TaskForm (forms.ModelForm):
    class Meta:
        model=Task
        fields=['text','deadline','priority']

class EditTaskForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['text','deadline','status','priority']

_1sem/December_4_Task/tasks/views.py
import time
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import F
from django.db.models import Q
from django.http import HttpResponse
from django.http import HttpResponseRedirect as Redirect
from django.shortcuts import render

# Create your views here.
from tasks.forms import EditTaskForm, TaskForm
from tasks.models import Task


def show_tasks (request):
    # task_list=Task.objects.all()
    # result="<br>".join([task.text for task in task_list])
    #
    # task_list = Task.objects.values_list("text",flat=True)
    # result = "<br>".join(task_list)
    # q1=Q(text__contains="Do")
    # q2 = Q(priority__gt=2)
    # q=q1|q2
    # task_list=Task.objects.filter(q)
    #task_list = Task.objects.filter(time_given__lt=F("deadline"))
    #result = "<br>".join([task.text for task in task_list])
    #return HttpResponse(result)
    return render(request,
                  "all_tasks.html",
                  {"tasks": Task.objects.all()})

def show_task (request,task_id):
    t=Task.objects.get(id=task_id)
    return HttpResponse ("<h1>Task # %s</h1>" %t)



def create_task(request):
    if request.user.is_authenticated():
        context = {}
        if 'text' in request.POST:
            f = TaskForm(request.POST)
            f.save()
            context["result"] = "Task created"
            return Redirect(reverse("tasks:all"))
        context["form"] = TaskForm()
        return render(request, "Add.html", context)
    else:
        return Redirect(reverse('login'))

@login_required(login_url=reverse_lazy('login'))
def edit_task(request, task_id):

    if "edit10" in request.session:
        if time.time() - request.session["edit10"]<10:
            return Redirect(reverse('tasks:all'))
        else:
            request.session["edit10"] = time.time()
    else:
        request.session["edit10"] = time.time()
    if request.method == "POST":
        task = Task.objects.get(id=task_id)
        f = EditTaskForm(request.POST, instance=task)
        f.save()
        return Redirect(reverse("tasks:all"))

    elif request.method == "GET":
        task = Task.objects.get(id=task_id)
        f = EditTaskForm(instance=task)
        return render(request,
                      "Edit.html",
                      {"form": f})
    else:
        return HttpResponse("Method is not supported")


def log_in(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password = password)
        if (user is not None):
            auth_login(request,user)
            return Redirect(reverse("tasks:all"))
        else:
            return Redirect (reverse('login'))
    else:
        return render(request,"log_in.html")

_1sem/December_4_Task/tasks/templates/Add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create task</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ result }}
    {{ form.as_p }}
    <input type="submit" value="Create task!">
</form>
</body>
</html>

_1sem/December_4_Task/tasks/templates/Edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>
<p><a href="{% url "tasks:all" %}">Back</a></p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="edit">
</form>
</body>
</html>

_1sem/December_4_Task/tasks/templates/all_tasks.html
{% extends "base.html" %}
{% block content %}
<marquee>My Beatiful Tasks</marquee>
    {% csrf_token %}
<table>
{% for task in tasks %}
    <tr>
    <td>
        {{ task }}
    </td>
    <td>
        <a href="{% url "tasks:edit_task" task.id %}">Edit</a>
    </td>
    </tr>
{% endfor %}
</table>
{% endblock %}

_1sem/December_4_Task/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <style>
        a, a:visited {
            color:black;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body style="Font-Family: Georgia; font-size: 16px;">

{% block content %}{% endblock %}

</body>
</html>

_1sem/December_4_Task/templates/log_in.html
{% extends "base.html" %}
{% block content %}
    <form action=" {%url "login" %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" />
    <input type="password" name="password" />
    <input type="submit" value="Login" />
    </form>
{% endblock %}