twoCh/feed/urls.py
from django.conf.urls import url

from feed import views

urlpatterns = [
    url(r'^$',views.home,name='home'),
    url(r'user/(?P<username>\w+)', views.list_tweets,name='list_tweets'),
    url(r'^cite$', views.cite, name="cite"),
    url(r'^retweet$', views.retweet, name="retweet"),
    url(r'^follow$', views.add_follower, name="follow"),
    url(r'^unfollow$', views.unfollow, name="unfollow"),
    url(r'^like$', views.like, name="like"),
    url(r'^head$', views.head_page, name="head"),
    url(r'^settings$', views.settings, name="settings"),
    url(r'^ajax_get_users$', views.ajax_get_users, name="ajax_get_users"),

]

twoCh/twoCh/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from feed import views

import feed
from twoCh import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'feed/', include('feed.urls',namespace='feed')),
    url(r'^login$', views.login,name='login'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twoCh/feed/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models



# Create your models here.


class GeneralTweet(models.Model):
    class Meta:
        abstract = True
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(default=datetime.datetime.today,verbose_name="Publication date")


class Retweet(GeneralTweet):
    tweet = models.ForeignKey("Tweet")
    def isRT(self):
        return True


class Tweet(GeneralTweet):
    text = models.TextField()
    image=models.ImageField(blank=True)
    def isRT(self):
        return False


    def __str__(self):
        return '%s : %s : %s' % (self.user,self.pub_date,self.text)

class Follow (models.Model):
    follower=models.ForeignKey(User,related_name="follower")
    followee=models.ForeignKey(User,related_name="followee")
    follow_date=models.DateTimeField(default=datetime.datetime.today)

class Like(models.Model):
    liker = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    tweet = models.ForeignKey(Tweet)
    def __str__(self):
        return "%s" % (self.liker.username)

twoCh/feed/views.py
from itertools import chain
from operator import attrgetter


from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.serializers import serialize
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.translation import ugettext as _

from feed.form import SettingsForm, TweetForm
from feed.models import Tweet, Retweet, Follow, Like
import json


# Create your views here.

@login_required
def home (request):
    if request.method == "POST":
        t = Tweet(user=request.user)
        f=TweetForm(request.POST,request.FILES,instance=t)
        f.save()
        return HttpResponseRedirect(reverse("feed:home"))
    t=TweetForm()
    tweets = Tweet.objects.all()
    retweets = Retweet.objects.all()
    tweets_n_retweets = sorted(chain(tweets, retweets), key=attrgetter('pub_date'), reverse=True)
    return render(request, "feed/home.html", {"items": tweets_n_retweets,'f':t},)


@login_required
def list_tweets(request,**kwargs):
    # tweets=Tweet.objects.filter(user__username=username).order_by("-pub_date")
    # return render(request,"feed/list_tweets.html", {'tweets':tweets})
    follow_list = Follow.objects.filter(follower__username=kwargs['username'])
    state = None
    folower=User.objects.get(username=kwargs['username'])
    for follow in follow_list:
        if follow.followee == request.user:
            state = _("You have read this user")
    if folower == request.user:
        state = _("This is your page")
    tweets = User.objects.get(username=kwargs['username']).tweet_set.order_by("-pub_date")
    return render(request, "feed/list_tweets.html", {"tweets": tweets,"username":kwargs['username'],"state":state,
                                                     'like': like})

@login_required
def cite(request):
    if request.method != "POST":
        return HttpResponse(_("Not supported"))
    t = Tweet(user=request.user)
    origin = Tweet.objects.get(id=request.POST["tweet_id"])
    t.text = 'RT @%s: "%s" on %s' % (origin.user.username,
                                     origin.text,
                                     origin.pub_date)
    t.save()
    return HttpResponseRedirect(reverse("feed:home"))


def retweet(request):
    if request.method != "POST":
        return HttpResponse(_("Not supported"))
    rt = Retweet(
        user=request.user,
        tweet_id=request.POST["tweet_id"]
    )
    rt.save()
    return HttpResponseRedirect(reverse("feed:home"))


def add_follower(request):
    if request.method != "POST":
        return HttpResponse (_("Not supported"))
    username=request.POST['user_name']
    follower=User.objects.get(username=username)
    follow = Follow(follower=follower,followee=request.user)
    follow.save()
    return HttpResponseRedirect (reverse("feed:list_tweets",kwargs={'username':username}))


def like(request):
    if request.method != "POST":
        return HttpResponse (_("Not supported"))
    tweet=Tweet.objects.get(id=request.POST['tweet_id'])
    try:
        like=Like.objects.get(liker=request.user,tweet=tweet)
        like.delete()
        like="e"
    except Exception:
        like=Like(liker=request.user,tweet=tweet)
        like.save()
    return HttpResponseRedirect(reverse('feed:list_tweets',kwargs={'username':tweet.user.username}))


def unfollow(request):
    user=User.objects.get(username=request.POST['user_name'])
    if request.method != "POST":
        return HttpResponse (_("Not supported"))
    try:
        follow=Follow.objects.get(follower=user,followee=request.user)
        follow.delete()
    except Exception:
        pass
    return HttpResponseRedirect(reverse('feed:list_tweets', kwargs={'username': user.username}))

def login (request):
    return render(request,'login.html')

def head_page (request):
    user=request.user
    print(user)
    return render(request,'feed/headPage.html',{'user':user})

def settings(request):
    if request.method=="POST":
        f=SettingsForm(request.POST)
        if f.is_valid():
            return HttpResponse(str(f.cleaned_data))
        else:
            return render(request, 'feed/settings.html', {'form': f})
    else:
        f=SettingsForm()
    #f.prefix="settings"

        return render(request,'feed/settings.html',{'form':f})
def ajax_get_users (request):
    # json_objects=serialize('json',User.objects.all(),fields=("username"))
    # return JsonResponse(json.loads(json_objects),safe=False)
    return HttpResponse("POST")

twoCh/feed/templates/feed/ad.html
{% extends 'base.html' %}
{% block header %}
    {% block login %}
        {% include 'login.html' %}
    {% endblock %}
{% endblock %}

twoCh/feed/templates/feed/headPage.html
{% extends 'base.html' %}
{% load i18n %}
{% block header %}
{% if user.is_anonymous %}
    {% block login %}
        {% include 'login.html' %}
    {% endblock %}
    {% block footer %}

    {% endblock %}
{% else %}
    {% block logo %}
            <h1>{% trans 'Welcome to Tweetter,' %} <a href="{% url 'feed:list_tweets' user.username %}">{{ user.username }}</a>!!</h1>
        {% endblock %}
{% endif %}
{% endblock %}

twoCh/feed/templates/feed/home.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load my_filters_and_tags %}
{% block include %}
    <link rel="stylesheet" type="text/css" href="{% static 'feed/style.css' %}"/>
{% endblock %}
{% block content %}
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ f.as_p }}
    <input type="submit" value="{% trans 'send' %}"/>
</form>
    <script type="application/javascript">
    $("textarea").val("This is default text")
    </script>
    {{ s |safe }}
    <p>{% trans "Authors:" %} {%  who items %}</p>
    <p>AJAX authors: <span id="ajax_authors"></span><button id="b1">Get</button> </p>

    {% comment %}<script type="application/javascript">
    $("#b1").click(function () {
        $.ajax({
            "url":"{% url 'feed:ajax_get_users' %}",
            "type": "get",
            "success":function (data) {
                $("#ajax_authors").html(data[0].fields.username)
                $("#b1").hide()
            },
            "failure":function(data){}
    })
    });
    </script>{% endcomment %}
    <script type="application/javascript">
    $("#b1").click(function () {
        $.ajax({
            "url":"{% url 'feed:ajax_get_users' %}",
            "type": "post ",
            "success":function (data) {
                $("#ajax_authors").html(data)
                $("#b1").hide()
            },
            "failure":function(data){}
    })
    });
    </script>

{% for t in items %}
    {% if t.isRT %}
        <i>{% trans "Retweeted by" %} {{ t.user }}</i>
        <p><b>{{ t.tweet.user }}: </b></p>
        <p>{{ t.tweet.text }} </p>
        <p><i> {{ t.tweet.pub_date }}</i></p>
        <hr/>
    {% else %}
        <p><b>{{ t.user }}: </b></p>
        <p>{{ t.image|render|safe }}</p>
        <p>{{ t.text }} </p>
        <p><i> {{ t.pub_date }}</i></p>
        <hr/>
    {% endif %}

{% endfor %}
{% endblock %}

twoCh/feed/templates/feed/list_tweets.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <h1>{% trans "Username:" %} {{ username }}</h1>
    <form method="post" action="{% url 'feed:follow' %}">
        {% csrf_token %}
    <input type="hidden" name="user_name" value="{{ username }}">
        {% if state %}
            <p>{{ state }}</p>
        {% else %}
    <input type="submit" value="Read" />
    {% endif %}
    </form>
    {% if not state == 'This is your page' %}
        <form method="POST" action="{% url 'feed:unfollow' %}">
            {% csrf_token %}
            <input type="hidden" name="user_name" value="{{ username }}">
            <input type="submit" value="{% trans 'Unfollow' %}"/>
        </form>
    {% endif %}
    <hr />
  {% for t in tweets %}

    <p><b>{{ t.user }}: </b>{{ t.text }} </p>
    <p><i> {{ t.pub_date }}</i></p>

          <form method="POST" action="{% url 'feed:retweet' %}">
              {% csrf_token %}
              <input type="hidden" name="tweet_id" value="{{ t.id }}"/>
              <input type="submit" value="{% trans 'Retweet' %}"/>
          </form>

           <form method="POST" action="{% url 'feed:cite' %}">
               {% csrf_token %}
               <input type="hidden" name="tweet_id" value="{{ t.id }}"/>
               <input type="submit" value="Cite"/>
           </form>

            <form method="POST" action="{% url 'feed:like' %}">
                {% csrf_token %}
                <input type="hidden" name="tweet_id" value="{{ t.id }}"/>
                <input type="submit" value="♥"/>
            </form>
    <hr/>

{% endfor %}
{% endblock %}

twoCh/feed/templates/feed/settings.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <form method="post" action="{% url 'feed:settings' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Submit' %}" />
    </form>
{% endblock %}

twoCh/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} Tweet</title>
</head>
    <body>
    {% block include %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    {% endblock %}
    <script type="application/javascript" src="{% static 'jquery.min.js' %}"></script>
    {% block header %}
        {% block logo %}
            <h1>Welcome to Tweetter</h1>
        {% endblock %}
        {% block login %}
        {% endblock %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block footer %}
        &copy; ITIS BARS Group Lab 2017
    {% endblock %}

    </body>

</html>

twoCh/templates/change_lang.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change</title>
</head>
<body>
{% trans 'Change your locale' %}:
<form action="/i18n/setlang/" method="POST">
  {% csrf_token %}
  <input name="next" type="hidden" value="/accounts/profile/" /><br/>
  <select name="language">
    {% for lang in LANGUAGES %}
      <option value="{{ lang.0 }}">{{ lang.1 }}</option>
    {% endfor %}
  </select><br/>
  <input type="submit" value="{% trans 'change' %}" />
</form>

</body>
</html>

twoCh/templates/forJquery.html
<!DOCTYPE html>
<html lang="en">
<style type="text/css">
    #btn2 {
        position: relative;
    }
</style>
<head>
    <script type="application/javascript" src="../static/jquery.min.js"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div id ="header">
    HELLO
</div>

<div id="content">
    <p>This is simple page</p>
    <p><textarea id="txt"></textarea></p>
    <p><button id="btn">Press me</button></p>
    <p><button id="btn2">Press me</button></p>
</div>
<div id="footer">
    Down
</div>

<script type="application/javascript">
    $(document).ready(function () {
      $("#btn").click(function () {
          if ($("#header").html()=="HELLO"){$("#header").html("GUTTEN TAG");
          }else {
              $("#header").html("HELLO");
          }
      });
        $("#btn2").click(function () {
            {% comment %}$("#txt").animate().hide(){% endcomment %}
            $("#btn2").animate({left:"+400"},"slow").animate({top:"400"},"slow").animate({left:"+20"},"slow");
        })
    });
</script>
</body>
</html>

twoCh/templates/js.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="application/javascript" src="sample.js"></script>
    <meta charset="UTF-8">
    <title>First</title>
</head>
<body>

<p id="main_greeting" class="greeting text2015"><b>hello</b></p>
<div id="greeting1" class="greeting">Hi hi</div>
<div id="greeting2" class="greeting">selem</div>
<div id="question1" class="question">olaaaa
    <input type="text" id="text_field" />
    <button onclick="fill()">fill the text</button>
</div>
<hr />
<button  onclick="f()">switch to goodbye</button>
<hr />

<input id="person-name" type="text" onchange="addToList()" />
<div id="list-of-name">

</div>

</body>
</html>

twoCh/templates/js2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Second</title>
</head>
<body>
<script type="application/javascript">
</script>

</body>
</html>

twoCh/templates/login.html
{% extends 'base.html' %}
    {% block login %}
        <div style="width: 1px">
            <form method="post" action="#">
                <input type="text" name="username" />
                <input type="password" name="password">
                <input type="submit" value="Login">
            </form>
        </div>
    {% endblock %}